"""empty message

Revision ID: b66da57b0cf0
Revises: None
Create Date: 2018-04-16 09:46:05.661030

"""

# revision identifiers, used by Alembic.
revision = 'b66da57b0cf0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('location', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'location', ['location'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'location')
    ### end Alembic commands ###
